<?php

declare(strict_types=1);

namespace Kreyu\Bundle\DataTableBundle\DependencyInjection;

use PhpOffice\PhpSpreadsheet\Spreadsheet as PhpSpreadsheet;
use Symfony\Component\Config\Definition\Builder\TreeBuilder;
use Symfony\Component\Config\Definition\ConfigurationInterface;

class Configuration implements ConfigurationInterface
{
    public function getConfigTreeBuilder(): TreeBuilder
    {
        $treeBuilder = new TreeBuilder('kreyu_data_table');

        $treeBuilder->getRootNode()
            ->children()
                ->arrayNode('themes')
                    ->scalarPrototype()->end()
                    ->beforeNormalization()->castToArray()->end()
                    ->defaultValue(['@KreyuDataTable/themes/bootstrap_5.html.twig'])
                ->end()
                ->arrayNode('defaults')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->scalarNode('column_factory')
                            ->defaultValue('kreyu_data_table.column.factory')
                        ->end()
                        ->scalarNode('request_handler')
                            ->defaultValue('kreyu_data_table.request_handler.http_foundation')
                        ->end()
                        ->arrayNode('sorting')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->booleanNode('enabled')
                                    ->defaultTrue()
                                ->end()
                                ->booleanNode('persistence_enabled')
                                    ->defaultFalse()
                                ->end()
                                ->scalarNode('persistence_adapter')
                                    ->defaultValue('kreyu_data_table.sorting.persistence.adapter.cache')
                                ->end()
                                ->scalarNode('persistence_subject_provider')
                                    ->defaultValue('kreyu_data_table.persistence.subject_provider.token_storage')
                                ->end()
                            ->end()
                        ->end()
                        ->arrayNode('pagination')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->booleanNode('enabled')
                                    ->defaultTrue()
                                ->end()
                                ->booleanNode('persistence_enabled')
                                    ->defaultFalse()
                                ->end()
                                ->scalarNode('persistence_adapter')
                                    ->defaultValue('kreyu_data_table.pagination.persistence.adapter.cache')
                                ->end()
                                ->scalarNode('persistence_subject_provider')
                                    ->defaultValue('kreyu_data_table.persistence.subject_provider.token_storage')
                                ->end()
                            ->end()
                        ->end()
                        ->arrayNode('filtration')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->booleanNode('enabled')
                                    ->defaultTrue()
                                ->end()
                                ->booleanNode('persistence_enabled')
                                    ->defaultFalse()
                                ->end()
                                ->scalarNode('persistence_adapter')
                                    ->defaultValue('kreyu_data_table.filtration.persistence.adapter.cache')
                                ->end()
                                ->scalarNode('persistence_subject_provider')
                                    ->defaultValue('kreyu_data_table.persistence.subject_provider.token_storage')
                                ->end()
                                ->scalarNode('filter_factory')
                                    ->defaultValue('kreyu_data_table.filter.factory')
                                ->end()
                                ->scalarNode('form_factory')
                                    ->defaultValue('form.factory')
                                ->end()
                            ->end()
                        ->end()
                        ->arrayNode('personalization')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->booleanNode('enabled')
                                    ->defaultTrue()
                                ->end()
                                ->booleanNode('persistence_enabled')
                                    ->defaultFalse()
                                ->end()
                                ->scalarNode('persistence_adapter')
                                    ->defaultValue('kreyu_data_table.personalization.persistence.adapter.cache')
                                ->end()
                                ->scalarNode('persistence_subject_provider')
                                    ->defaultValue('kreyu_data_table.persistence.subject_provider.token_storage')
                                ->end()
                                ->scalarNode('form_factory')
                                    ->defaultValue('form.factory')
                                ->end()
                            ->end()
                        ->end()
                        ->arrayNode('exporting')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->booleanNode('enabled')
                                    ->defaultValue(class_exists(PhpSpreadsheet::class))
                                ->end()
                                ->scalarNode('exporter_factory')
                                    ->defaultValue('kreyu_data_table.exporter.factory')
                                ->end()
                                ->scalarNode('form_factory')
                                    ->defaultValue('form.factory')
                                ->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
            ->end()
        ;

        return $treeBuilder;
    }
}
