<?php

namespace ContainerQU1WZRw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getKreyuDataTable_Twig_DataTableExtensionService extends Kreyu_Bundle_DataTableBundle_Tests_Fixtures_KernelTestDebugContainer
{
    /**
     * Gets the private 'kreyu_data_table.twig.data_table_extension' shared service.
     *
     * @return \Kreyu\Bundle\DataTableBundle\Twig\DataTableExtension
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/twig/twig/src/Extension/ExtensionInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/twig/twig/src/Extension/AbstractExtension.php';
        include_once \dirname(__DIR__, 4).'/src/Twig/DataTableExtension.php';

        return $container->privates['kreyu_data_table.twig.data_table_extension'] = new \Kreyu\Bundle\DataTableBundle\Twig\DataTableExtension();
    }
}
