<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQU1WZRw\Kreyu_Bundle_DataTableBundle_Tests_Fixtures_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQU1WZRw/Kreyu_Bundle_DataTableBundle_Tests_Fixtures_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerQU1WZRw.legacy');

    return;
}

if (!\class_exists(Kreyu_Bundle_DataTableBundle_Tests_Fixtures_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerQU1WZRw\Kreyu_Bundle_DataTableBundle_Tests_Fixtures_KernelTestDebugContainer::class, Kreyu_Bundle_DataTableBundle_Tests_Fixtures_KernelTestDebugContainer::class, false);
}

return new \ContainerQU1WZRw\Kreyu_Bundle_DataTableBundle_Tests_Fixtures_KernelTestDebugContainer([
    'container.build_hash' => 'QU1WZRw',
    'container.build_id' => '6171654e',
    'container.build_time' => 1700323497,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQU1WZRw');
