name: Code Quality

on:
  push:
  pull_request:
  workflow_dispatch:
    paths:
      - '**.php'

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: dom fileinfo filter libxml xmlreader zip gd

      - name: Install dependencies
        uses: ramsey/composer-install@v2

      - name: Run php-cs-fixer
        run: ./vendor/bin/php-cs-fixer fix --diff

      - name: Commit php-cs-fixer changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply php-cs-fixer changes

  phpstan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: dom fileinfo filter libxml xmlreader zip gd

      - name: Install dependencies
        uses: ramsey/composer-install@v2

      - name: Run PHPStan
        run: ./vendor/bin/phpstan analyse